### ISSUE TITLE
RabbitMQ connection error: MarchHare::ChannelAlreadyClosed causes an infinite opening of connections in RabbitMQ

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-rabbitmq#10]
From @DKribl: https://github.com/elastic/logstash/issues/3360

-------

Hey,

I get following error (infrequent) while shipping logs to RabbitMQ:

```
{:timestamp=>"2015-06-02T10:12:12.822000+0200", :message=>"RabbitMQ connection error: MarchHare::ChannelAlreadyClosed. Will attempt to reconnect in 10 seconds...", :exception=>#<MarchHare::ChannelAlreadyClosed: MarchHare::ChannelAlreadyClosed>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:965:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:963:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:595:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:40:in `publish_serialized'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/json.rb:44:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:31:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):26:in `output_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:error}
```

For every reconnect, there is a new channel and connection being created. So after a few minutes there are tons of connections opened in RabbitMQ. At this point, there is no data coming into RMQ anymore. I have to kill the process of the shipper because the service won't stop. ( It says:  "logstash stop failed; still running) After starting up logstash again it works fine for a few minutes.
Because this error is infrequent and Logstash is normally sending Logs to RabbitMQ, I dont think its a configuration issue... Well I hope so. 

Here's my output config:

    output {
      rabbitmq {
        codec => "json"
        persistent => true
        host => "myconsumerip"
        durable => true
        key => "logstash-key"
        exchange => "logstash-exchange"
        exchange_type => "direct"
        user => "admin_iw"
        password => "mypassword"
        port => 5672
        ssl => false
        verify_ssl => false
        vhost => "logstash"
      }
    }

I updated Logstash to 1.5.0-1 because of [this](https://logstash.jira.com/browse/LOGSTASH-1886) post, but it didn't help. That's why I decided to make a new Post about this kind of issue. I hope you guys can help me :)

**Comment by parabolic** [comment]
It's happening to me as well here's the report,

**System**
```
Ubuntu 14.04.1 LTS
```
**Logstash_version**
```
1:1.5.0-1
```
**Conf**
```
UDP input
No filters
Rabbitmq ssl output
```
**Kernel**
```
3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
After restarting the rabbitmq server logstash is not able to reconect to rabbitmq and it needs to be restarted. I get the following error in the logs. And I see a lot of connects from that ip in the rabbitmq server.
** Logstash log **
```
{:timestamp=>"2015-06-09T13:02:20.348000+0000", :message=>"RabbitMQ connection error: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0). Will attempt to reconnect in 10 seconds...", :exception=>#<MarchHare::ChannelAlreadyClosed: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:965:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:963:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:595:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:40:in `publish_serialized'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/json.rb:44:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:31:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:79:in `worker_setup'"], :level=>:error}
```
**Rabbitmq server log**
```
=INFO REPORT==== 9-Jun-2015::14:51:49 ===
accepting AMQP connection
```
again and again

Logstash at this point cannot be restarted with /etc/init.d/logstash restart and it needs to be killed with -9. After that everything works fine.

**Comment by ssc-** [comment]
I had the same problems. The following change fixed the problem for me: 612a6d71193e789b73eac8d6c0114b74b25745c0.

It's more or less the first time I had to patch some ruby code, but it definitely looks like whenever a reconnect happened, a new connection was opened without being assigned to the class member @x.

### Testing/Demo (on FreeBSD):

##### Normal behaviour
```
# procstat -f $(pgrep -f java.*logstash)|grep TCP
3780 java               11 s - rw-------   1       0 TCP ::ffff:10.0.8.24.51408 ::ffff:10.0.0.33.5672
```

##### After we drop the connection
```
# tcpdrop -la |grep 10.0.0.33.5672|sh
10.0.0.12 51408 10.0.0.33 5672: dropped
```

##### .. and wait for some time - we see something like this:
```
# procstat -f $(pgrep -f java.*logstash)|grep TCP
3780 java               12 s - rw-------   1       0 TCP ::ffff:10.0.0.12.33249 ::ffff:10.0.0.33.5672
3780 java               17 s - rw-------   1       0 TCP ::ffff:10.0.0.12.22576 ::ffff:10.0.0.33.5672
3780 java               18 s - rw-------   1       0 TCP ::ffff:10.0.0.12.46642 ::ffff:10.0.0.33.5672
3780 java               20 s - rw-------   1       0 TCP ::ffff:10.0.0.12.25844 ::ffff:10.0.0.33.5672
3780 java               21 s - rw-------   1       0 TCP ::ffff:10.0.0.12.13095 ::ffff:10.0.0.33.5672
3780 java               22 s - rw-------   1       0 TCP ::ffff:10.0.0.12.25006 ::ffff:10.0.0.33.5672
3780 java               23 s - rw-------   1       0 TCP ::ffff:10.0.0.12.26599 ::ffff:10.0.0.33.5672
3780 java               24 s - rw-------   1       0 TCP ::ffff:10.0.0.12.22265 ::ffff:10.0.0.33.5672
3780 java               25 s - rw-------   1       0 TCP ::ffff:10.0.0.12.64354 ::ffff:10.0.0.33.5672
3780 java               26 s - rw-------   1       0 TCP ::ffff:10.0.0.12.21805 ::ffff:10.0.0.33.5672
3780 java               27 s - rw-------   1       0 TCP ::ffff:10.0.0.12.25460 ::ffff:10.0.0.33.5672
3780 java               28 s - rw-------   1       0 TCP ::ffff:10.0.0.12.52093 ::ffff:10.0.0.33.5672
3780 java               29 s - rw-------   1       0 TCP ::ffff:10.0.0.12.44740 ::ffff:10.0.0.33.5672
3780 java               30 s - rw-------   1       0 TCP ::ffff:10.0.0.12.25201 ::ffff:10.0.0.33.5672
3780 java               31 s - rw-------   1       0 TCP ::ffff:10.0.0.12.64149 ::ffff:10.0.0.33.5672
3780 java               32 s - rw-------   1       0 TCP ::ffff:10.0.0.12.60565 ::ffff:10.0.0.33.5672
3780 java               33 s - rw-------   1       0 TCP ::ffff:10.0.0.12.40647 ::ffff:10.0.0.33.5672
3780 java               34 s - rw-------   1       0 TCP ::ffff:10.0.0.12.41559 ::ffff:10.0.0.33.5672
3780 java               35 s - rw-------   1       0 TCP ::ffff:10.0.0.12.59310 ::ffff:10.0.0.33.5672
3780 java               36 s - rw-------   1       0 TCP ::ffff:10.0.0.12.17290 ::ffff:10.0.0.33.5672
3780 java               37 s - rw-------   1       0 TCP ::ffff:10.0.0.12.58013 ::ffff:10.0.0.33.5672
```

**Comment by dforste** [comment]
@ssc is there a reason you do not have a PR for your changes. I am having the same issue.

**Comment by parabolic** [comment]
@ssc-  Thanks we've already applied the fix to one of our production machines works good fso far I am going to patch the file manually until a new version with a fix gets out. 
Thanks!!

**Comment by dforste** [comment]
@ssc Thanks for creating https://github.com/logstash-plugins/logstash-output-rabbitmq/pull/12 
I am pretty sure they will want a https://www.elastic.co/contributor-agreement signed if you haven't already.

**Comment by ssc-** [comment]
@dforste Thanks for the hint, just signed the CLA.

**Comment by DKribl** [comment]
@ssc- I applied your fix, hopefully it will work now. I'll give a quick feedback after testing.

**Comment by DKribl** [comment]
Everything works fine now!
Thanks :+1:

**Comment by andrewvc** [comment]
This should be fixed in the 1.1.1 release. If you encounter any new issues please reopen this issue.

**Comment by Akshaykapoor** [comment]
Im still facing this issue, and when this happens logstash essentially halts the entire pipeline. Only way I've got it to work is by restarting the service. 

```
{:timestamp=>"2016-11-10T18:55:02.326000+0000", :message=>"MarchHare::ChannelAlreadyClosed", :exception=>MarchHare::ChannelAlreadyClosed, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:976:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:974:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:606:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-3.0.9-java/lib/logstash/outputs/rabbitmq.rb:54:in `publish'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb:42:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-3.0.9-java/lib/logstash/outputs/rabbitmq.rb:47:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:129:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}
{:timestamp=>"2016-11-10T18:55:02.658000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-11-10T18:55:02.660000+0000", :message=>"CircuitBreaker::Open", :name=>"Beats input", :level=>:warn}
{:timestamp=>"2016-11-10T18:55:02.661000+0000", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::OpenBreaker, :level=>:warn}
{:timestamp=>"2016-11-10T18:55:03.160000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-11-10T18:55:03.330000+0000", :message=>"MarchHare::ChannelAlreadyClosed", :exception=>MarchHare::ChannelAlreadyClosed, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:976:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:974:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/channel.rb:606:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-3.0.9-java/lib/logstash/outputs/rabbitmq.rb:54:in `publish'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-2.1.3/lib/logstash/codecs/json.rb:42:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-3.0.9-java/lib/logstash/outputs/rabbitmq.rb:47:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/outputs/base.rb:83:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:129:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}
```

I'm using logstash v 2.3.1. I should also mention, there are no issues in elasticsearch logs when this happens.
